config_version = 2

[backdrop]
enabled = true

[bar.default]
start = [ "control-center", "workspaces" ]
center = [ "date", "spacer_1", "clock" ]
end = [ "media", "notifications", "clipboard", "wallpaper", "wallhaven", "group:g1", "group:g2", "session" ]
concave_edge_corners = false
margin_edge = 0
margin_ends = 8
position = "left"
radius = 16
radius_bottom_left = 0
radius_top_left = 0
shadow = true
contact_shadow = true

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "network", "bluetooth" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "volume", "brightness", "battery" ]
    opacity = 1.0
    padding = 6.0

[brightness]
minimum_brightness = 0.01

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "power_profile"

[dock]
shadow = false

[location]
auto_locate = true
custom_schedule = true
sunrise = "06:00"
sunset = "21:00"

[nightlight]
enabled = true
temperature_night = 1000

[plugin_settings."noctalia/notes"]
panel_placement = "floating"

[plugins]
enabled = [ "noctalia/timer", "noctalia/translator", "noctalia/wallhaven" ]

[shell]
date_format = "%F (%A)"
telemetry_enabled = true

    [shell.panel]
    shadow = false

    [shell.screenshot]
    save_to_file = false

[theme]
builtin = "Ayu"
community_palette = "Oxocarbon"
mode = "dark"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4" ]

[wallpaper]
fill_mode = "fit"
transition_on_startup = true

[widget.audio_visualizer]
bands = 32
capsule = true
color_2 = "tertiary"
mirrored = false

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.date]
format = "{:%y %m %d}"

[widget.network]
show_label = false

[widget.spacer_1]
type = "spacer"
anchor = true

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"
